import type {
  ModelAttributeColumnOptions,
  DataType,
  Model,
  ModelStatic,
  TableName,
} from 'sequelize';

/**
 * Normalized category for a column's data type, used by the schema layer to map to Zod types.
 * Stable across dialects (e.g. INTEGER, BIGINT → 'integer').
 */
export type DataTypeCategory =
  | 'integer'
  | 'float'
  | 'string'
  | 'text'
  | 'boolean'
  | 'date'
  | 'uuid'
  | 'json'
  | 'blob'
  | 'enum'
  | 'array'
  | 'geometry'
  | 'other';

/**
 * Descriptor used by the schema layer to map a column to a Zod type.
 *
 * This structure provides a normalized representation of column configuration,
 * combining type, nullability, default value, generation, and enum constraints.
 *
 * It enables decoupling of schema metadata from ORM-specific implementations, allowing
 * code such as Zod schema generation or API contracts to reason about column properties
 * in a database-agnostic way.
 *
 * @remarks
 * - The `dataTypeCategory` represents a normalized type, such as 'integer', 'string', etc.,
 *   that remains stable regardless of the underlying SQL type.
 * - `allowNull` specifies if the column allows null values.
 * - `hasDefault` is true if the column has a default value defined in the schema.
 * - `isGenerated` indicates if the column is auto-generated by the database (identity/serial, etc.).
 * - If the column is an enum, `enumValues` contains the allowed string values.
 *
 * @see ColumnBuilder.getSchemaDescriptor
 * @see {@link ColumnSchemaDescriptor}
 * @see {@link https://sequelize.org/api/v7/class/src/model.js~Model.html#instance-member-rawAttributes | Sequelize rawAttributes}
 */
export interface ColumnSchemaDescriptor {
  dataTypeCategory: DataTypeCategory;
  allowNull: boolean;
  hasDefault: boolean;
  isGenerated: boolean;
  enumValues?: readonly string[];
}

export class ColumnBuilder<T = any> {
  #config: Partial<ModelAttributeColumnOptions>;
  #dataTypeCategory: DataTypeCategory;

  constructor(type: DataType, category: DataTypeCategory) {
    this.#config = { type };
    this.#dataTypeCategory = category;
  }

  primaryKey(): this {
    this.#config.primaryKey = true;
    return this;
  }

  autoIncrement(): this {
    if (!['integer', 'float'].includes(this.#dataTypeCategory)) {
      throw new Error(
        `autoIncrement() can only be used with numeric types (INTEGER, BIGINT, etc.), not ${this.#dataTypeCategory}`,
      );
    }
    this.#config.autoIncrement = true;
    return this;
  }

  autoIncrementIdentity(): this {
    if (!['integer', 'float'].includes(this.#dataTypeCategory)) {
      throw new Error(
        `autoIncrementIdentity() can only be used with numeric types, not ${this.#dataTypeCategory}`,
      );
    }
    this.#config.autoIncrementIdentity = true;
    return this;
  }

  allowNull(value: boolean = true): this {
    this.#config.allowNull = value;
    return this;
  }

  notNull(): this {
    this.#config.allowNull = false;
    return this;
  }

  unique(value: boolean | string | { name: string; msg: string } = true) {
    this.#config.unique = value;
    return this;
  }

  defaultValue(value: T | (() => T)): this {
    this.#config.defaultValue = value;
    return this;
  }

  comment(text: string): this {
    this.#config.comment = text;
    return this;
  }

  references(options: {
    model: TableName | ModelStatic<any>;
    key: string;
    deferrable?: any;
  }): this {
    this.#config.references = options;
    return this;
  }

  onDelete(action: 'CASCADE' | 'SET NULL' | 'RESTRICT' | 'NO ACTION' | 'SET DEFAULT'): this {
    if (!this.#config.references) {
      throw new Error('onDelete() can only be used when references() is set');
    }
    this.#config.onDelete = action;
    return this;
  }

  onUpdate(action: 'CASCADE' | 'SET NULL' | 'RESTRICT' | 'NO ACTION' | 'SET DEFAULT'): this {
    if (!this.#config.references) {
      throw new Error('onUpdate() can only be used when references() is set');
    }
    this.#config.onUpdate = action;
    return this;
  }

  field(name: string): this {
    this.#config.field = name;
    return this;
  }

  validate(rules: Record<string, any>): this {
    this.#config.validate = rules;
    return this;
  }

  get(fn: (this: Model) => T): this {
    this.#config.get = fn;
    return this;
  }

  set(fn: (this: Model, val: T) => void): this {
    this.#config.set = fn;
    return this;
  }

  values(arr: readonly string[]): this {
    if (this.#dataTypeCategory !== 'enum') {
      throw new Error('values() can only be used with ENUM types');
    }
    this.#config.values = arr;
    return this;
  }

  /**
   * Returns a {@link ColumnSchemaDescriptor} for Zod schema generation.
   * Used by {@link getDescriptors} when building schemas from ColumnBuilder attributes.
   *
   * @returns A descriptor with dataTypeCategory, allowNull, hasDefault, isGenerated, and optional enumValues.
   */
  getSchemaDescriptor(): ColumnSchemaDescriptor {
    return {
      dataTypeCategory: this.#dataTypeCategory,
      allowNull: this.#config.allowNull ?? true,
      hasDefault: this.#config.defaultValue !== undefined,
      isGenerated: this.#config.autoIncrementIdentity === true,
      enumValues:
        this.#dataTypeCategory === 'enum' && this.#config.values ? this.#config.values : undefined,
    };
  }

  build(): ModelAttributeColumnOptions {
    if (this.#config.autoIncrement && this.#config.primaryKey === false) {
      throw new Error('autoIncrement columns should typically be primary keys');
    }

    if (this.#config.autoIncrement && this.#config.defaultValue !== undefined) {
      throw new Error('autoIncrement columns cannot have defaultValue');
    }

    if ((this.#config.onDelete || this.#config.onUpdate) && !this.#config.references) {
      throw new Error('onDelete/onUpdate require references to be set');
    }

    // oxlint-disable-next-line typescript-eslint/no-unsafe-type-assertion -- #config is fully populated at runtime
    return this.#config as ModelAttributeColumnOptions;
  }
}
